Repository scrapy/parsel, pull requests merged in 2019-11, with the labels that each got.

#165 Add explanation for argument 'base_url'
  parsel/selector.py
Labels: docs, enhancement

#169 Install the sphinx-notfound-page Sphinx extension
  docs/conf.py
  tox.ini
Labels: docs, enhancement

#172 Add pytest-flake8
  .travis.yml
  conftest.py
  pytest.ini
  tox.ini
Labels: enhancement

#175 Create docs/requirements.txt
  docs/requirements.txt
  tox.ini
Labels: bug, docs

#173 Add bandit to CI
  .bandit.yml
  .travis.yml
  tox.ini
Labels: enhancement
